module.exports = {
  roles: {
    USER: 'USER',
    ADMIN: 'ADMIN',
  },
  status: {
    INACTIVE: 'INACTIVE',
    ACTIVE: 'ACTIVE',
    BANNED: 'BANNED',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    UNVERIFIED: 'UNVERIFIED',
  },
  gender: {
    MALE: 'male',
    FEMALE: 'female',
  },
  requestStatus: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED'
  },
  paymentType: {
    PURCHASE: 'PURCHASE',
    SUBSCRIPTION: 'SUBSCRIPTION',
  },
  notificationType: {
    PICTURE_REQUEST: 'PICTURE_REQUEST',
    PICTURE_REQUEST_REJECTED: 'PICTURE_REQUEST_REJECTED',
    PICTURE_SENT: 'PICTURE_SENT',
    CONTACT_DETAILS_REQUEST: 'CONTACT_DETAILS_REQUEST',
    CONTACT_DETAILS_SENT: 'CONTACT_DETAILS_SENT',
    CONTACT_DETAILS_REQUEST_REJECTED: 'CONTACT_DETAILS_REQUEST_REJECTED',
    CONTACT_DETAILS_SENT_REJECTED: 'CONTACT_DETAILS_SENT_REJECTED',
    MATCH_CREATED: 'MATCH_CREATED',
    MATCH_CANCELLED: 'MATCH_CANCELLED',
  },
  apiPrefix: '/dev/mahaba/api/v1',
}
